### ISSUE TITLE
2.0.0 support

### ISSUE THREAD

**Issue by xxyy** [mantisbt-plugins/Taskodrome#81]
I just upgraded my Mantis installation to 2.0.0-rc.2. I noticed that Taskodrome is not yet fully compatible with that version. Changing the target version in `Taskodrome.php` to `2.0.0` allows me to enable the plugin, but does not show the link to Taskodrome/main in the new navbar and causes an error trying to access the plugin config page. The main page remains white with a JavaScript error in the console.

I believe that support for 2.0.0 should be added soon, since the second Release Candiate has already been published, probably meaning that there will be a release coming in the not-so-far future.

**Comment by AuthenticEshkinKot** [comment]
Hi, @xxyy !
I started working on support of 2.0.0 couple of weeks ago and I have some progress. I am planning to push a separate branch for 2.0.0 till the end of this week.

**Comment by AuthenticEshkinKot** [comment]
Hi, @xxyy 
I've added support of MantisBT 2.0.0. You can get appropriate version of the plugin from https://github.com/mantisbt-plugins/Taskodrome/tree/mantisbt_2.0.0 or from master branch - there is no difference between them.
Unfortunately, there is no link on the plugin in bugtracker's new sidebar, because old way was removed and as I know, there is no new way to add it. To get access to the plugin you should use this link - http://your/path/to/mantisbt/plugin.php?page=Taskodrome/main (in my case it is http://localhost/mantisbt-2.0.0/plugin.php?page=Taskodrome/main). Hope this problem will be solved soon.

**Comment by xxyy** [comment]
@AuthenticEshkinKot works perfectly for me, thanks a lot!

I took a look at the icon, see #89.
